# SPDX-FileCopyrightText: 2026 roolrz
# SPDX-License-Identifier: Apache-2.0

[package]
name = "hyper-tool-args-shared"
workspace = "../../../app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
crate-type = ["dylib"]
test = false
bench = false
doctest = false

[dependencies]
implementation = { package = "hyper-tool-args", path = ".." }
hyper-rust-std.workspace = true

[lints]
workspace = true
