[package]
name = "hyper"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "Apache-2.0"
description = "A modular, Rust-based type-1 hypervisor kernel"
publish = false

[features]
default = []
kernel-self-test = []

[lib]
test = false
bench = false
doctest = false

[[bin]]
name = "hyper"
path = "src/main.rs"
test = false
bench = false

[dependencies]
rustc-demangle = { version = "0.1.28", default-features = false }

[lints.clippy]
expect_used = "deny"
unwrap_used = "deny"

[profile.kernel]
inherits = "release"
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
lto = true
opt-level = 2
overflow-checks = true
panic = "abort"
rpath = false
split-debuginfo = "off"
strip = "none"
