/* SPDX-FileCopyrightText: 2026 roolrz
 * SPDX-License-Identifier: Apache-2.0
 */

.section .text._start, "ax", @progbits
.p2align 2
.global _start
.type _start, @function
_start:
    mv a1, sp
    li t0, 65536
    sub sp, sp, t0
    tail __hyper_userspace_start
.size _start, . - _start
.global __hyper_userspace_enter
.hidden __hyper_userspace_enter
.type __hyper_userspace_enter, @function
__hyper_userspace_enter:
    mv sp, a0
    li s0, 0
    li ra, 0
    jr a1
.size __hyper_userspace_enter, . - __hyper_userspace_enter

.section .note.GNU-stack, "", @progbits
