# SPDX-FileCopyrightText: 2026 roolrz
# SPDX-License-Identifier: Apache-2.0

[package]
name = "hyper-rt"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Language runtime entry for freestanding HypeR Native Rust applications"

[dependencies]
hyper-abi = { path = "../../abi" }
hyper-os = { path = "../hyper-os" }
hyper-sys = { path = "../hyper-sys" }

[lints]
workspace = true
