# SPDX-FileCopyrightText: 2026 roolrz
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "3"
members = [
    "init",
    "session",
    "console-input",
    "console-output",
    "shell",
    "echo",
    "cat",
    "mv",
    "ln",
    "rm",
    "chmod",
    "cp",
    "mkdir",
    "rmdir",
    "touch",
    "ps",
    "handle",
    "ls",
    "free",
    "top",
    "vm-manager",
    "vm-runtime",
    "vm-smoke",
    "vmm",
    "vm-policy",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/roolrz/HypeR"
publish = false

[workspace.dependencies]
hyper-os = "=0.0.0"
hyper-rt = { version = "=0.0.0", features = ["std"] }
hyper-service = "=0.0.0"
hyper-vm-image = "=0.0.0"
hyper-vm-policy = { path = "vm-policy" }
clap = { version = "=4.6.6", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shlex = "=1.3.0"

[workspace.lints.clippy]
doc_markdown = "deny"
empty_docs = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
undocumented_unsafe_blocks = "deny"
unimplemented = "deny"
unreachable = "deny"
unwrap_used = "deny"
missing_safety_doc = "deny"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("hyper"))'] }
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
codegen-units = 1
debug = 1
incremental = false
lto = "fat"
opt-level = "s"
overflow-checks = true
panic = "abort"
strip = "none"
