# SPDX-FileCopyrightText: 2026 roolrz
# SPDX-License-Identifier: Apache-2.0

[package]
name = "hyper-fit-pack"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
hyper-vm-image = { path = "../../sdk/rust/hyper-vm-image" }

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
