[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tsrc/arch/aarch64/linker.ld",
    "-C", "link-arg=--gc-sections",
    "-C", "link-arg=--no-eh-frame-hdr",
    "-C", "link-arg=-pie",
    "-C", "link-arg=-z",
    "-C", "link-arg=norelro",
    "-C", "link-arg=--pack-dyn-relocs=relr",
    "-C", "relocation-model=pic",
    "-C", "target-feature=+outline-atomics",
    "-C", "force-frame-pointers=yes",
]
