# SPDX-FileCopyrightText: 2026 roolrz
# SPDX-License-Identifier: Apache-2.0

[package]
name = "hyper-std-smoke"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
hyper-abi = "=0.0.0"
hyper-sys = "=0.0.0"
hyper-os = { version = "=0.0.0", features = ["std"] }
hyper-rt = { version = "=0.0.0", features = ["std"] }
clap = { version = "=4.6.6", features = ["derive", "env"] }

[profile.release]
panic = "abort"
