#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 roolrz
# SPDX-License-Identifier: Apache-2.0

"""Build a new flashable GPT image from board policy and immutable build artifacts."""

import argparse
import binascii
import hashlib
import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import tempfile

from board_config import Board, GPT_ENTRIES, GPT_ENTRY_BYTES, GPT_TABLE_SECTORS, SECTOR


def gpt(board):
    entries = bytearray(GPT_ENTRIES * GPT_ENTRY_BYTES)
    for index, part in enumerate(board.partitions):
        # VM containers intentionally have a project type GUID, never a host FS type.
        struct.pack_into('<16s16sQQQ72s', entries, index * GPT_ENTRY_BYTES,
                         part.type_id.bytes_le, part.identifier.bytes_le,
                         part.start, part.end, 0, ('hyper-' + part.name).encode('utf-16-le'))
    checksum = binascii.crc32(entries)

    def header(current, alternate, table):
        result = bytearray(SECTOR)
        struct.pack_into('<8sIIIIQQQQ16sQIII', result, 0, b'EFI PART', 0x10000, 92, 0, 0,
                         current, alternate, 2 + GPT_TABLE_SECTORS,
                         board.disk_sectors - GPT_TABLE_SECTORS - 2,
                         board.disk_id.bytes_le, table, GPT_ENTRIES, GPT_ENTRY_BYTES, checksum)
        struct.pack_into('<I', result, 16, binascii.crc32(result[:92]))
        return result

    mbr = bytearray(SECTOR)
    struct.pack_into('<B3sB3sII', mbr, 446, 0, b'\0\2\0', 0xee, b'\xff\xff\xff',
                     1, min(board.disk_sectors - 1, 0xffffffff))
    mbr[510:512] = b'\x55\xaa'
    last = board.disk_sectors - 1
    return [(0, mbr), (1, header(1, last, 2)), (2, entries),
            (last - GPT_TABLE_SECTORS, entries),
            (last, header(last, 1, last - GPT_TABLE_SECTORS))]


def digest(path):
    with path.open('rb') as stream:
        return hashlib.file_digest(stream, 'sha256').hexdigest()


def sparse_copy(source, destination, offset, capacity):
    """Bound writes to one volume; preserve zero extents in newly created images."""
    remaining = source.stat().st_size
    if remaining > capacity:
        raise ValueError(f'artifact exceeds its partition: {source}')
    with source.open('rb') as stream:
        destination.seek(offset)
        while remaining:
            chunk = stream.read(min(1024 * 1024, remaining))
            if not chunk:
                raise ValueError(f'artifact shortened during packing: {source}')
            if chunk.count(0) == len(chunk):
                destination.seek(len(chunk), os.SEEK_CUR)
            else:
                destination.write(chunk)
            remaining -= len(chunk)
        if stream.read(1):
            raise ValueError(f'artifact grew during packing: {source}')


def prepare_payload(board, artifacts, directory):
    required = set(board.source['files'].values()) | {
        part.image for part in board.partitions if part.image}
    if artifacts.keys() != required:
        raise ValueError(f'artifact keys differ: missing={required - artifacts.keys()}, '
                         f'unknown={artifacts.keys() - required}')
    for key, path in artifacts.items():
        if not path.is_file() or path.stat().st_size == 0:
            raise ValueError(f'missing or empty {key} artifact: {path}')
    for part in board.partitions:
        if part.image and artifacts[part.image].stat().st_size != part.sectors * SECTOR:
            # In particular, never silently enlarge a guest GPT disk and strand its
            # backup header in the middle. Resize with the guest's own image tooling.
            raise ValueError(f'{part.image}: disk image must exactly match the configured volume size')
    for target, key in board.source['files'].items():
        destination = directory / target
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(artifacts[key], destination)
    for filename, content in [('board.json', board.source), ('volumes.json', board.volumes()),
                              ('vms.json', board.vms())]:
        (directory / filename).write_text(json.dumps(content, indent=2) + '\n')
    if board.source['boot'] == 'rpi5-tfa':
        for filename in ('config.txt', 'cmdline.txt'):
            if filename in board.source['files']:
                raise ValueError(f'{filename} is generated by the boot profile')
        (directory / 'config.txt').write_text(
            '[pi5]\narmstub=bl31.bin\nkernel=hyper.img\n'
            'initramfs bootstrap.cpio followkernel\ncmdline=cmdline.txt\n'
            'uart_2ndstage=1\ncamera_auto_detect=0\ndisplay_auto_detect=0\n[all]\n')
        (directory / 'cmdline.txt').write_text('earlycon=pl011,0x107d001000,115200n8 loglevel=7\n')

def _find_executable(program, directories=()):
    """Find an executable in PATH and then in additional directories."""
    resolved = shutil.which(program)
    if resolved:
        return resolved

    for directory in directories:
        path = Path(directory) / program
        if path.is_file() and os.access(path, os.X_OK):
            return str(path)

    return None

def image_tool(program, default, formula):
    # 1. Respect PATH first.
    resolved = _find_executable(program)
    if resolved:
        return resolved

    # 2. Search common Linux sbin locations.
    linux_sbin_dirs = (
        "/usr/local/sbin",
        "/usr/sbin",
        "/sbin",
    )
    resolved = _find_executable(program, linux_sbin_dirs)
    if resolved:
        return resolved

    # 3. Search Homebrew's bin/sbin.
    #
    # Only use brew when looking for the default program, preserving the
    # existing behavior where an explicitly overridden executable remains
    # authoritative.
    brew = shutil.which("brew") if program == default else None
    if brew:
        try:
            prefix = subprocess.run(
                [brew, "--prefix", formula],
                check=True,
                capture_output=True,
                text=True,
                timeout=10,
            ).stdout.strip()

            if prefix and Path(prefix).is_absolute():
                resolved = _find_executable(
                    program,
                    (
                        Path(prefix) / "bin",
                        Path(prefix) / "sbin",
                    ),
                )
                if resolved:
                    return resolved

        except (
            OSError,
            subprocess.CalledProcessError,
            subprocess.TimeoutExpired,
        ):
            pass

    raise ValueError(
        f"{program} was not found; install {formula} "
        "or provide its executable path"
    )


def build(board, artifacts, output, mkfs='mkfs.fat', mcopy='mcopy'):
    if output.exists() or output.is_symlink():
        raise ValueError('refusing to overwrite an existing image; choose a new output path')
    mkfs = image_tool(mkfs, 'mkfs.fat', 'dosfstools')
    mcopy = image_tool(mcopy, 'mcopy', 'mtools')
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='.board-image-', dir=output.parent) as temporary:
        staging = Path(temporary)
        payload = staging / 'payload'
        payload.mkdir()
        checksums = {key: digest(path) for key, path in artifacts.items()}
        prepare_payload(board, artifacts, payload)
        config = staging / 'config.fat'
        with config.open('xb') as stream:
            stream.truncate(board.partitions[0].sectors * SECTOR)
        subprocess.run([mkfs, '--invariant', '-F', '32', '-S', str(SECTOR), '-n', 'HYPER',
                        '-i', f'{board.disk_id.int & 0xffffffff:08x}', str(config)], check=True)
        subprocess.run([mcopy, '-i', str(config), '-s',
                        *(str(item) for item in sorted(payload.iterdir())), '::/'], check=True)
        image = staging / 'disk.img'
        with image.open('xb') as stream:
            stream.truncate(board.disk_sectors * SECTOR)
            for sector, contents in gpt(board):
                stream.seek(sector * SECTOR)
                stream.write(contents)
            sparse_copy(config, stream, board.partitions[0].start * SECTOR,
                        board.partitions[0].sectors * SECTOR)
            for part in board.partitions[1:]:
                if part.image:
                    sparse_copy(artifacts[part.image], stream, part.start * SECTOR,
                                part.sectors * SECTOR)
            stream.flush()
            os.fsync(stream.fileno())
        if checksums != {key: digest(path) for key, path in artifacts.items()}:
            raise ValueError('artifacts changed while packing; retry')
        # Atomic no-replace publication, including races with another packer.
        os.link(image, output)
    print(f'{output}: {board.disk_sectors * SECTOR} bytes; {len(board.partitions)} volumes')


def artifact_inputs(board, defaults, explicit):
    """Select build defaults by policy, but reject typos in explicit inputs."""
    def pairs(items):
        result = {}
        for item in items:
            key, separator, path = item.partition('=')
            if not separator or not key or not path or key in result:
                raise ValueError('artifacts must be unique NAME=PATH pairs')
            result[key] = Path(path)
        return result

    required = set(board.source['files'].values()) | {
        part.image for part in board.partitions if part.image}
    selected = {key: path for key, path in pairs(defaults).items() if key in required}
    overrides = pairs(explicit)
    if overrides.keys() - required:
        raise ValueError(f'unknown explicit artifacts: {overrides.keys() - required}')
    selected.update(overrides)
    if selected.keys() != required:
        raise ValueError(f'missing artifacts: {required - selected.keys()}')
    return selected


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--board', required=True, type=Path)
    parser.add_argument('--output', type=Path)
    parser.add_argument('--artifact', action='append', default=[], metavar='NAME=PATH')
    parser.add_argument('--default-artifact', action='append', default=[], metavar='NAME=PATH',
                        help='build default, selected only when referenced by board policy')
    parser.add_argument('--plan', action='store_true', help='validate and print volume layout only')
    parser.add_argument('--mkfs', default='mkfs.fat')
    parser.add_argument('--mcopy', default='mcopy')
    args = parser.parse_args()
    try:
        board = Board.load(args.board)
        if args.plan:
            print(json.dumps(board.volumes(), indent=2))
            return
        if args.output is None:
            raise ValueError('--output is required when building an image')
        artifacts = artifact_inputs(board, args.default_artifact, args.artifact)
        build(board, artifacts, args.output, args.mkfs, args.mcopy)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f'board image: {error}\n')


if __name__ == '__main__':
    main()
