//! x86-64 architectural constants shared with assembly.

pub const R_X86_64_RELATIVE: u64 = 8;
pub const PAGE_SHIFT: u64 = 12;
pub const PAGE_SIZE: u64 = 1 << PAGE_SHIFT;
pub const PAGE_PRESENT: u64 = 1 << 0;
pub const PAGE_WRITE: u64 = 1 << 1;
pub const PAGE_USER: u64 = 1 << 2;
pub const PAGE_WRITE_THROUGH: u64 = 1 << 3;
pub const PAGE_CACHE_DISABLE: u64 = 1 << 4;
pub const PAGE_LARGE: u64 = 1 << 7;
pub const PAGE_GLOBAL: u64 = 1 << 8;
pub const PAGE_NO_EXECUTE: u64 = 1 << 63;
pub const PHYSICAL_ADDRESS_LIMIT: u64 = 1 << 46;
pub const PML4_KERNEL_BASE: u64 = 0xffff_8000_0000_0000;
pub const PML4_LINEAR_BASE: u64 = 0xffff_9000_0000_0000;
pub const PML4_MMIO_BASE: u64 = 0xffff_a000_0000_0000;
pub const PML4_STACK_BASE: u64 = 0xffff_b000_0000_0000;

pub const THREAD_CONTEXT_RBX_OFFSET: u64 = 0;
pub const THREAD_CONTEXT_RBP_OFFSET: u64 = 8;
pub const THREAD_CONTEXT_R12_OFFSET: u64 = 16;
pub const THREAD_CONTEXT_R13_OFFSET: u64 = 24;
pub const THREAD_CONTEXT_R14_OFFSET: u64 = 32;
pub const THREAD_CONTEXT_R15_OFFSET: u64 = 40;
pub const THREAD_CONTEXT_RSP_OFFSET: u64 = 48;
pub const THREAD_CONTEXT_RIP_OFFSET: u64 = 56;
pub const THREAD_CONTEXT_SIZE: u64 = 64;

pub const VCPU_CONTEXT_RAX_OFFSET: u64 = 0;
pub const VCPU_CONTEXT_RBX_OFFSET: u64 = 8;
pub const VCPU_CONTEXT_RCX_OFFSET: u64 = 16;
pub const VCPU_CONTEXT_RDX_OFFSET: u64 = 24;
pub const VCPU_CONTEXT_RSP_OFFSET: u64 = 32;
pub const VCPU_CONTEXT_RBP_OFFSET: u64 = 40;
pub const VCPU_CONTEXT_RSI_OFFSET: u64 = 48;
pub const VCPU_CONTEXT_RDI_OFFSET: u64 = 56;
pub const VCPU_CONTEXT_R8_OFFSET: u64 = 64;
pub const VCPU_CONTEXT_R9_OFFSET: u64 = 72;
pub const VCPU_CONTEXT_R10_OFFSET: u64 = 80;
pub const VCPU_CONTEXT_R11_OFFSET: u64 = 88;
pub const VCPU_CONTEXT_R12_OFFSET: u64 = 96;
pub const VCPU_CONTEXT_R13_OFFSET: u64 = 104;
pub const VCPU_CONTEXT_R14_OFFSET: u64 = 112;
pub const VCPU_CONTEXT_R15_OFFSET: u64 = 120;
pub const VCPU_CONTEXT_RIP_OFFSET: u64 = 128;
pub const VCPU_CONTEXT_RFLAGS_OFFSET: u64 = 136;
pub const VCPU_CONTEXT_FX_STATE_OFFSET: u64 = 192;

pub const ASM_CONSTANTS: &[(&str, u64)] = &[
    ("R_X86_64_RELATIVE", R_X86_64_RELATIVE),
    ("PAGE_SHIFT", PAGE_SHIFT),
    ("PAGE_PRESENT", PAGE_PRESENT),
    ("PAGE_WRITE", PAGE_WRITE),
    ("PAGE_LARGE", PAGE_LARGE),
    ("THREAD_CONTEXT_RBX_OFFSET", THREAD_CONTEXT_RBX_OFFSET),
    ("THREAD_CONTEXT_RBP_OFFSET", THREAD_CONTEXT_RBP_OFFSET),
    ("THREAD_CONTEXT_R12_OFFSET", THREAD_CONTEXT_R12_OFFSET),
    ("THREAD_CONTEXT_R13_OFFSET", THREAD_CONTEXT_R13_OFFSET),
    ("THREAD_CONTEXT_R14_OFFSET", THREAD_CONTEXT_R14_OFFSET),
    ("THREAD_CONTEXT_R15_OFFSET", THREAD_CONTEXT_R15_OFFSET),
    ("THREAD_CONTEXT_RSP_OFFSET", THREAD_CONTEXT_RSP_OFFSET),
    ("THREAD_CONTEXT_RIP_OFFSET", THREAD_CONTEXT_RIP_OFFSET),
    ("VCPU_CONTEXT_FX_STATE_OFFSET", VCPU_CONTEXT_FX_STATE_OFFSET),
    ("VCPU_CONTEXT_RAX_OFFSET", VCPU_CONTEXT_RAX_OFFSET),
    ("VCPU_CONTEXT_RBX_OFFSET", VCPU_CONTEXT_RBX_OFFSET),
    ("VCPU_CONTEXT_RCX_OFFSET", VCPU_CONTEXT_RCX_OFFSET),
    ("VCPU_CONTEXT_RDX_OFFSET", VCPU_CONTEXT_RDX_OFFSET),
    ("VCPU_CONTEXT_RBP_OFFSET", VCPU_CONTEXT_RBP_OFFSET),
    ("VCPU_CONTEXT_RSI_OFFSET", VCPU_CONTEXT_RSI_OFFSET),
    ("VCPU_CONTEXT_RDI_OFFSET", VCPU_CONTEXT_RDI_OFFSET),
    ("VCPU_CONTEXT_R8_OFFSET", VCPU_CONTEXT_R8_OFFSET),
    ("VCPU_CONTEXT_R9_OFFSET", VCPU_CONTEXT_R9_OFFSET),
    ("VCPU_CONTEXT_R10_OFFSET", VCPU_CONTEXT_R10_OFFSET),
    ("VCPU_CONTEXT_R11_OFFSET", VCPU_CONTEXT_R11_OFFSET),
    ("VCPU_CONTEXT_R12_OFFSET", VCPU_CONTEXT_R12_OFFSET),
    ("VCPU_CONTEXT_R13_OFFSET", VCPU_CONTEXT_R13_OFFSET),
    ("VCPU_CONTEXT_R14_OFFSET", VCPU_CONTEXT_R14_OFFSET),
    ("VCPU_CONTEXT_R15_OFFSET", VCPU_CONTEXT_R15_OFFSET),
];
