# SPDX-FileCopyrightText: 2026 roolrz
# SPDX-License-Identifier: Apache-2.0

[package]
name = "hyper-vm-support"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
autotests = false

[dependencies]
hyper-os = { workspace = true, features = ["std"] }
hyper-service.workspace = true
hyper-vm-image.workspace = true

[features]
startup-profile = []

[lints]
workspace = true
