// SPDX-FileCopyrightText: 2026 roolrz
// SPDX-License-Identifier: Apache-2.0

//! RISC-V architectural constants shared with assembly startup code.

pub const R_RISCV_RELATIVE: u64 = 3;
pub const SATP_MODE_SV39: u64 = 8 << 60;
pub const SSTATUS_SIE: u64 = 1 << 1;
pub const SSTATUS_SPIE: u64 = 1 << 5;
pub const SSTATUS_SPP: u64 = 1 << 8;
pub const SIE_SSIE: u64 = 1 << 1;
pub const SIE_STIE: u64 = 1 << 5;
pub const SIE_SEIE: u64 = 1 << 9;

// Hypervisor-extension controls used when entering a VS-mode guest.
pub const HEDELEG_GUEST_VALUE: u64 = 0x0000_b1ff;
pub const HIDELEG_GUEST_VALUE: u64 = 0x0000_0444;
pub const HCOUNTEREN_GUEST_VALUE: u64 = 1 << 1;
pub const HVIP_GUEST_MASK: u64 = (1 << 2) | (1 << 6) | (1 << 10);
pub const HSTATUS_SPV: u64 = 1 << 7;
pub const HSTATUS_SPVP: u64 = 1 << 8;
pub const HSTATUS_VTVM: u64 = 1 << 20;
pub const HSTATUS_VTW: u64 = 1 << 21;
pub const HSTATUS_VTSR: u64 = 1 << 22;
pub const HSTATUS_VSXL_64: u64 = 2 << 32;
pub const HSTATUS_GUEST_CLEAR: u64 = HSTATUS_VTVM | HSTATUS_VTSR | (3 << 32);
pub const HSTATUS_GUEST_SET: u64 = HSTATUS_SPV | HSTATUS_SPVP | HSTATUS_VTW | HSTATUS_VSXL_64;
pub const SSTATUS_GUEST_SPP: u64 = 1 << 8;
pub const GUEST_HS_ANCHOR_RA_OFFSET: u64 = 0;
pub const GUEST_HS_ANCHOR_S0_OFFSET: u64 = 8;
pub const GUEST_HS_ANCHOR_GP_OFFSET: u64 = 104;
pub const GUEST_HS_ANCHOR_TP_OFFSET: u64 = 112;
pub const GUEST_HS_ANCHOR_CONTEXT_OFFSET: u64 = 120;
pub const GUEST_HS_ANCHOR_FLOATING_OFFSET: u64 = 128;
pub const GUEST_HS_ANCHOR_FCSR_OFFSET: u64 = 384;
pub const GUEST_HS_ANCHOR_FS_OFFSET: u64 = 392;
pub const GUEST_HS_ANCHOR_SCOUNTEREN_OFFSET: u64 = 400;
pub const GUEST_HS_ANCHOR_SENVCFG_OFFSET: u64 = 408;
pub const GUEST_HS_ANCHOR_SIZE: u64 = 416;
pub const GUEST_ANCHOR_EXIT_IRQ_TAIL: u64 = 1;
pub const TRAP_ACTION_RESUME: u64 = 0;
pub const TRAP_ACTION_POSTLUDE: u64 = 1;
pub const TRAP_ACTION_ANCHOR_IRQ_TAIL: u64 = 2;

pub const PAGE_SHIFT: u64 = 12;
pub const PAGE_SIZE: u64 = 1 << PAGE_SHIFT;
pub const PHYSICAL_ADDRESS_LIMIT: u64 = 1 << 56;
pub const SV39_ADDRESS_MASK: u64 = (1 << 39) - 1;
pub const SV39_KERNEL_BASE: u64 = 0xffff_ffc0_0000_0000;
pub const SV39_LINEAR_BASE: u64 = 0xffff_ffd0_0000_0000;
pub const SV39_MMIO_BASE: u64 = 0xffff_ffe0_0000_0000;
pub const SV39_STACK_BASE: u64 = 0xffff_fff0_0000_0000;

pub const PTE_VALID: u64 = 1 << 0;
pub const PTE_READ: u64 = 1 << 1;
pub const PTE_WRITE: u64 = 1 << 2;
pub const PTE_EXECUTE: u64 = 1 << 3;
pub const PTE_USER: u64 = 1 << 4;
pub const PTE_GLOBAL: u64 = 1 << 5;
pub const PTE_ACCESSED: u64 = 1 << 6;
pub const PTE_DIRTY: u64 = 1 << 7;
pub const PTE_PPN_SHIFT: u64 = 10;

pub const HGATP_MODE_SV39X4: u64 = 8 << 60;
pub const HGATP_VMID_SHIFT: u64 = 44;
pub const HGATP_VMID_MASK: u64 = 0x3fff << HGATP_VMID_SHIFT;
pub const STAGE2_IPA_LIMIT: u64 = 1 << 41;
pub const THREAD_CONTEXT_S0_OFFSET: u64 = 0;
pub const THREAD_CONTEXT_RA_OFFSET: u64 = 96;
pub const THREAD_CONTEXT_SP_OFFSET: u64 = 104;
pub const THREAD_CONTEXT_SIE_OFFSET: u64 = 112;
pub const THREAD_CONTEXT_SIZE: u64 = 128;
pub const VCPU_GENERAL_OFFSET: u64 = 0;
pub const VCPU_PC_OFFSET: u64 = 256;
pub const VCPU_VSSTATUS_OFFSET: u64 = 264;
pub const VCPU_VSIE_OFFSET: u64 = 272;
pub const VCPU_VSTVEC_OFFSET: u64 = 280;
pub const VCPU_VSSCRATCH_OFFSET: u64 = 288;
pub const VCPU_VSEPC_OFFSET: u64 = 296;
pub const VCPU_VSCAUSE_OFFSET: u64 = 304;
pub const VCPU_VSTVAL_OFFSET: u64 = 312;
pub const VCPU_HVIP_OFFSET: u64 = 320;
pub const VCPU_VSATP_OFFSET: u64 = 328;
pub const VCPU_VSTIMECMP_OFFSET: u64 = 336;
pub const VCPU_SCOUNTEREN_OFFSET: u64 = 344;
pub const VCPU_SENVCFG_OFFSET: u64 = 352;
pub const VCPU_VIRTUAL_COUNT_OFFSET: u64 = 360;
pub const VCPU_FLOATING_OFFSET: u64 = 368;
pub const VCPU_FCSR_OFFSET: u64 = 624;
pub const VCPU_RUN_STATE_OFFSET: u64 = 632;
pub const TRAP_FRAME_GENERAL_OFFSET: u64 = 0;
pub const TRAP_FRAME_RA_OFFSET: u64 = 8;
pub const TRAP_FRAME_SP_OFFSET: u64 = 16;
pub const TRAP_FRAME_GP_OFFSET: u64 = 24;
pub const TRAP_FRAME_TP_OFFSET: u64 = 32;
pub const TRAP_FRAME_T0_OFFSET: u64 = 40;
pub const TRAP_FRAME_T1_OFFSET: u64 = 48;
pub const TRAP_FRAME_T2_OFFSET: u64 = 56;
pub const TRAP_FRAME_S0_OFFSET: u64 = 64;
pub const TRAP_FRAME_S1_OFFSET: u64 = 72;
pub const TRAP_FRAME_A0_OFFSET: u64 = 80;
pub const TRAP_FRAME_A1_OFFSET: u64 = 88;
pub const TRAP_FRAME_A2_OFFSET: u64 = 96;
pub const TRAP_FRAME_A3_OFFSET: u64 = 104;
pub const TRAP_FRAME_A4_OFFSET: u64 = 112;
pub const TRAP_FRAME_A5_OFFSET: u64 = 120;
pub const TRAP_FRAME_A6_OFFSET: u64 = 128;
pub const TRAP_FRAME_A7_OFFSET: u64 = 136;
pub const TRAP_FRAME_S2_OFFSET: u64 = 144;
pub const TRAP_FRAME_S3_OFFSET: u64 = 152;
pub const TRAP_FRAME_S4_OFFSET: u64 = 160;
pub const TRAP_FRAME_S5_OFFSET: u64 = 168;
pub const TRAP_FRAME_S6_OFFSET: u64 = 176;
pub const TRAP_FRAME_S7_OFFSET: u64 = 184;
pub const TRAP_FRAME_S8_OFFSET: u64 = 192;
pub const TRAP_FRAME_S9_OFFSET: u64 = 200;
pub const TRAP_FRAME_S10_OFFSET: u64 = 208;
pub const TRAP_FRAME_S11_OFFSET: u64 = 216;
pub const TRAP_FRAME_T3_OFFSET: u64 = 224;
pub const TRAP_FRAME_T4_OFFSET: u64 = 232;
pub const TRAP_FRAME_T5_OFFSET: u64 = 240;
pub const TRAP_FRAME_T6_OFFSET: u64 = 248;
pub const TRAP_FRAME_SEPC_OFFSET: u64 = 256;
pub const TRAP_FRAME_SSTATUS_OFFSET: u64 = 264;
pub const TRAP_FRAME_SCAUSE_OFFSET: u64 = 272;
pub const TRAP_FRAME_STVAL_OFFSET: u64 = 280;
pub const TRAP_FRAME_HTVAL_OFFSET: u64 = 288;
pub const TRAP_FRAME_HTINST_OFFSET: u64 = 296;
pub const TRAP_FRAME_GUEST_ORIGIN_OFFSET: u64 = 304;
pub const TRAP_FRAME_GUEST_ANCHOR_RETURN_OFFSET: u64 = 312;
pub const TRAP_FRAME_HOST_CPU_INDEX_OFFSET: u64 = 320;
pub const TRAP_FRAME_GUEST_CONTEXT_OFFSET: u64 = 328;
pub const TRAP_FRAME_SIZE: u64 = 336;

pub const ASM_CONSTANTS: &[(&str, u64)] = &[
    ("R_RISCV_RELATIVE", R_RISCV_RELATIVE),
    ("SATP_MODE_SV39", SATP_MODE_SV39),
    ("SSTATUS_SIE", SSTATUS_SIE),
    ("SSTATUS_SPIE", SSTATUS_SPIE),
    ("HEDELEG_GUEST_VALUE", HEDELEG_GUEST_VALUE),
    ("HIDELEG_GUEST_VALUE", HIDELEG_GUEST_VALUE),
    ("HCOUNTEREN_GUEST_VALUE", HCOUNTEREN_GUEST_VALUE),
    ("HVIP_GUEST_MASK", HVIP_GUEST_MASK),
    ("HSTATUS_SPV", HSTATUS_SPV),
    ("HSTATUS_GUEST_CLEAR", HSTATUS_GUEST_CLEAR),
    ("HSTATUS_GUEST_SET", HSTATUS_GUEST_SET),
    ("SSTATUS_GUEST_SPP", SSTATUS_GUEST_SPP),
    ("GUEST_HS_ANCHOR_RA_OFFSET", GUEST_HS_ANCHOR_RA_OFFSET),
    ("GUEST_HS_ANCHOR_S0_OFFSET", GUEST_HS_ANCHOR_S0_OFFSET),
    ("GUEST_HS_ANCHOR_GP_OFFSET", GUEST_HS_ANCHOR_GP_OFFSET),
    ("GUEST_HS_ANCHOR_TP_OFFSET", GUEST_HS_ANCHOR_TP_OFFSET),
    (
        "GUEST_HS_ANCHOR_CONTEXT_OFFSET",
        GUEST_HS_ANCHOR_CONTEXT_OFFSET,
    ),
    (
        "GUEST_HS_ANCHOR_FLOATING_OFFSET",
        GUEST_HS_ANCHOR_FLOATING_OFFSET,
    ),
    ("GUEST_HS_ANCHOR_FCSR_OFFSET", GUEST_HS_ANCHOR_FCSR_OFFSET),
    ("GUEST_HS_ANCHOR_FS_OFFSET", GUEST_HS_ANCHOR_FS_OFFSET),
    (
        "GUEST_HS_ANCHOR_SCOUNTEREN_OFFSET",
        GUEST_HS_ANCHOR_SCOUNTEREN_OFFSET,
    ),
    (
        "GUEST_HS_ANCHOR_SENVCFG_OFFSET",
        GUEST_HS_ANCHOR_SENVCFG_OFFSET,
    ),
    ("GUEST_HS_ANCHOR_SIZE", GUEST_HS_ANCHOR_SIZE),
    ("GUEST_ANCHOR_EXIT_IRQ_TAIL", GUEST_ANCHOR_EXIT_IRQ_TAIL),
    ("TRAP_ACTION_RESUME", TRAP_ACTION_RESUME),
    ("TRAP_ACTION_POSTLUDE", TRAP_ACTION_POSTLUDE),
    ("TRAP_ACTION_ANCHOR_IRQ_TAIL", TRAP_ACTION_ANCHOR_IRQ_TAIL),
    ("PAGE_SHIFT", PAGE_SHIFT),
    ("THREAD_CONTEXT_S0_OFFSET", THREAD_CONTEXT_S0_OFFSET),
    ("THREAD_CONTEXT_RA_OFFSET", THREAD_CONTEXT_RA_OFFSET),
    ("THREAD_CONTEXT_SP_OFFSET", THREAD_CONTEXT_SP_OFFSET),
    ("THREAD_CONTEXT_SIE_OFFSET", THREAD_CONTEXT_SIE_OFFSET),
    ("VCPU_GENERAL_OFFSET", VCPU_GENERAL_OFFSET),
    ("VCPU_PC_OFFSET", VCPU_PC_OFFSET),
    ("VCPU_VSSTATUS_OFFSET", VCPU_VSSTATUS_OFFSET),
    ("VCPU_VSIE_OFFSET", VCPU_VSIE_OFFSET),
    ("VCPU_VSTVEC_OFFSET", VCPU_VSTVEC_OFFSET),
    ("VCPU_VSSCRATCH_OFFSET", VCPU_VSSCRATCH_OFFSET),
    ("VCPU_VSEPC_OFFSET", VCPU_VSEPC_OFFSET),
    ("VCPU_VSCAUSE_OFFSET", VCPU_VSCAUSE_OFFSET),
    ("VCPU_VSTVAL_OFFSET", VCPU_VSTVAL_OFFSET),
    ("VCPU_HVIP_OFFSET", VCPU_HVIP_OFFSET),
    ("VCPU_VSATP_OFFSET", VCPU_VSATP_OFFSET),
    ("VCPU_VSTIMECMP_OFFSET", VCPU_VSTIMECMP_OFFSET),
    ("VCPU_SCOUNTEREN_OFFSET", VCPU_SCOUNTEREN_OFFSET),
    ("VCPU_SENVCFG_OFFSET", VCPU_SENVCFG_OFFSET),
    ("VCPU_VIRTUAL_COUNT_OFFSET", VCPU_VIRTUAL_COUNT_OFFSET),
    ("VCPU_FLOATING_OFFSET", VCPU_FLOATING_OFFSET),
    ("VCPU_FCSR_OFFSET", VCPU_FCSR_OFFSET),
    ("VCPU_RUN_STATE_OFFSET", VCPU_RUN_STATE_OFFSET),
    ("TRAP_FRAME_GENERAL_OFFSET", TRAP_FRAME_GENERAL_OFFSET),
    ("TRAP_FRAME_RA_OFFSET", TRAP_FRAME_RA_OFFSET),
    ("TRAP_FRAME_SP_OFFSET", TRAP_FRAME_SP_OFFSET),
    ("TRAP_FRAME_GP_OFFSET", TRAP_FRAME_GP_OFFSET),
    ("TRAP_FRAME_TP_OFFSET", TRAP_FRAME_TP_OFFSET),
    ("TRAP_FRAME_T0_OFFSET", TRAP_FRAME_T0_OFFSET),
    ("TRAP_FRAME_T1_OFFSET", TRAP_FRAME_T1_OFFSET),
    ("TRAP_FRAME_T2_OFFSET", TRAP_FRAME_T2_OFFSET),
    ("TRAP_FRAME_S0_OFFSET", TRAP_FRAME_S0_OFFSET),
    ("TRAP_FRAME_S1_OFFSET", TRAP_FRAME_S1_OFFSET),
    ("TRAP_FRAME_A0_OFFSET", TRAP_FRAME_A0_OFFSET),
    ("TRAP_FRAME_A1_OFFSET", TRAP_FRAME_A1_OFFSET),
    ("TRAP_FRAME_A2_OFFSET", TRAP_FRAME_A2_OFFSET),
    ("TRAP_FRAME_A3_OFFSET", TRAP_FRAME_A3_OFFSET),
    ("TRAP_FRAME_A4_OFFSET", TRAP_FRAME_A4_OFFSET),
    ("TRAP_FRAME_A5_OFFSET", TRAP_FRAME_A5_OFFSET),
    ("TRAP_FRAME_A6_OFFSET", TRAP_FRAME_A6_OFFSET),
    ("TRAP_FRAME_A7_OFFSET", TRAP_FRAME_A7_OFFSET),
    ("TRAP_FRAME_S2_OFFSET", TRAP_FRAME_S2_OFFSET),
    ("TRAP_FRAME_S3_OFFSET", TRAP_FRAME_S3_OFFSET),
    ("TRAP_FRAME_S4_OFFSET", TRAP_FRAME_S4_OFFSET),
    ("TRAP_FRAME_S5_OFFSET", TRAP_FRAME_S5_OFFSET),
    ("TRAP_FRAME_S6_OFFSET", TRAP_FRAME_S6_OFFSET),
    ("TRAP_FRAME_S7_OFFSET", TRAP_FRAME_S7_OFFSET),
    ("TRAP_FRAME_S8_OFFSET", TRAP_FRAME_S8_OFFSET),
    ("TRAP_FRAME_S9_OFFSET", TRAP_FRAME_S9_OFFSET),
    ("TRAP_FRAME_S10_OFFSET", TRAP_FRAME_S10_OFFSET),
    ("TRAP_FRAME_S11_OFFSET", TRAP_FRAME_S11_OFFSET),
    ("TRAP_FRAME_T3_OFFSET", TRAP_FRAME_T3_OFFSET),
    ("TRAP_FRAME_T4_OFFSET", TRAP_FRAME_T4_OFFSET),
    ("TRAP_FRAME_T5_OFFSET", TRAP_FRAME_T5_OFFSET),
    ("TRAP_FRAME_T6_OFFSET", TRAP_FRAME_T6_OFFSET),
    ("TRAP_FRAME_SEPC_OFFSET", TRAP_FRAME_SEPC_OFFSET),
    ("TRAP_FRAME_SSTATUS_OFFSET", TRAP_FRAME_SSTATUS_OFFSET),
    ("TRAP_FRAME_SCAUSE_OFFSET", TRAP_FRAME_SCAUSE_OFFSET),
    ("TRAP_FRAME_STVAL_OFFSET", TRAP_FRAME_STVAL_OFFSET),
    ("TRAP_FRAME_HTVAL_OFFSET", TRAP_FRAME_HTVAL_OFFSET),
    ("TRAP_FRAME_HTINST_OFFSET", TRAP_FRAME_HTINST_OFFSET),
    (
        "TRAP_FRAME_GUEST_ORIGIN_OFFSET",
        TRAP_FRAME_GUEST_ORIGIN_OFFSET,
    ),
    (
        "TRAP_FRAME_GUEST_ANCHOR_RETURN_OFFSET",
        TRAP_FRAME_GUEST_ANCHOR_RETURN_OFFSET,
    ),
    (
        "TRAP_FRAME_HOST_CPU_INDEX_OFFSET",
        TRAP_FRAME_HOST_CPU_INDEX_OFFSET,
    ),
    (
        "TRAP_FRAME_GUEST_CONTEXT_OFFSET",
        TRAP_FRAME_GUEST_CONTEXT_OFFSET,
    ),
    ("TRAP_FRAME_SIZE", TRAP_FRAME_SIZE),
];
